# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Garripoli/Desktop/giufla/projectSineWave/cores/PLL2/PLL2.xci
# IP: The module: 'PLL2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Garripoli/Desktop/giufla/projectSineWave/cores/PLL2/PLL2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Garripoli/Desktop/giufla/projectSineWave/cores/PLL2/PLL2.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Garripoli/Desktop/giufla/projectSineWave/cores/PLL2/PLL2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Garripoli/Desktop/giufla/projectSineWave/cores/PLL2/PLL2.xci
# IP: The module: 'PLL2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Garripoli/Desktop/giufla/projectSineWave/cores/PLL2/PLL2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Garripoli/Desktop/giufla/projectSineWave/cores/PLL2/PLL2.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Garripoli/Desktop/giufla/projectSineWave/cores/PLL2/PLL2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
